### ISSUE TITLE
Black Cursor Color

### ISSUE THREAD

**Issue by the-c0d3r** [pslobo/Quiver-Theme-Atom-One-Dark#1]
I really love this color theme. But it has one problem though. The cursor color become black most of the time. The background is also dark, and when the cursor become black, it is barely visible. A temporary fix I could do was to switch back to one of the default themes, and then switching it back to Atom one dark again. I also scanned the theme json file for cursor color. But couldn't find any. I don't know if it is a problem with the Quiver, or something interfering with the Quiver's ability to render the cursor, or your theme somehow set the color. 
PS : It seems to turn to black only inside Markdown cells. 

<img width="652" alt="screen shot 2016-09-30 at 8 17 05 pm" src="https://cloud.githubusercontent.com/assets/4526565/18991406/f62b722a-874a-11e6-9eda-c29843f65118.png">
<img width="749" alt="screen shot 2016-09-30 at 8 16 21 pm" src="https://cloud.githubusercontent.com/assets/4526565/18991407/f6725668-874a-11e6-9610-1f587bec1e32.png">

**Comment by pslobo** [comment]
Weird. As you can see from this screenshot, my cursor is blue (as should be).

![screen shot 2016-09-30 at 14 10 24](https://cloud.githubusercontent.com/assets/1452095/18992713/c04fe9e8-8717-11e6-8555-ad6e599da2c6.png)

What versions are you running (OS, Quiver etc.)

**Comment by the-c0d3r** [comment]
I'm running macOS Sierra (10.12) and Quiver is 3.0.3 (88) which I believe is the lastest version available on app store. I did edited the Quiver's settings -> Styles (CSS). But those are only the font and font sizes. Is there possibility that I might have made any changes to the cursor color? Thanks for responding so quick. 
By the way, is the default color should be blue? or your theme's cursor color should be blue? For me, if it is not black, it was white.

**Comment by pslobo** [comment]
Ok, I think I know what's going on. The cursor color is defined in the Ace Editor Theme.

In the json file I've got:

```
"editor": {
    "codeCellTheme": "tomorrow_night_eighties",
    "markdownCellTheme": "tomorrow_night_eighties"
  },
```

In my case, I've altered the Ace Editor Theme `tomorrow_night_eighties` and added `.ace-tomorrow-night-eighties .ace_cursor{color:#528BFF}`.

You can read the instructions [here](https://github.com/pslobo/Quiver-Theme-Atom-One-Dark#%EF%B8%8F-experimental-%EF%B8%8F) It's says experimental, but I've been using this without problems.

**Comment by the-c0d3r** [comment]
Oh, when i installed your theme, I just downloaded the theme json file and added to Quiver. I did replaced the `tomorrow_night_eighties.js` file. The theme for code cell also chose Tomorrow night eighties. The color for cursor in code cell did change to blue, but the cursor inside markdown cell is still black. Any other ideas?

**Comment by the-c0d3r** [comment]
Thanks for telling me your edit of the `tomorrow_night_eighties` file. I didn't know `.ace_cursor` can be used to edit the color. I just added that in Editor styles to overwrite the color and now it's blue. Thanks a lot for helping me. 

``` css
.markdown-cell .ace_cursor {
  color:#528BFF;
}
```

**Comment by pslobo** [comment]
Excellent! Happy to have helped!. I'll try and finish porting the Ace Editor Theme and hopefully that'll get included in the future. Until then, adding that info in the Editor Styles may be a good alternative indeed!
